export enum PokemonType {
  Normal = "normal",
  Fire = "fire",
  Water = "water",
  Eléctrico = "eléctrico",
  Grass = "grass",
  Ice = "ice",
  Fighting = "fighting",
  Poison = "poison",
  Ground = "ground",
  Flying = "flying",
  Psíquico = "psíquico",
  Bug = "bug",
  Rock = "rock",
  Ghost = "ghost",
  Dragon = "dragon",
  Dark = "dark",
  Steel = "steel",
  Hada = "hada",
}
