export enum PokemonType {
  Normal = "normal",
  Fuego = "fuego",
  Agua = "agua",
  Eléctrico = "eléctrico",
  Planta = "planta",
  Hielo = "hielo",
  Lucha = "lucha",
  Veneno = "veneno",
  Tierra = "tierra",
  Volador = "volador",
  Psíquico = "psíquico",
  Bicho = "bicho",
  Roca = "roca",
  Fantasma = "fantasma",
  Dragón = "dragón",
  Siniestro = "siniestro",
  Acero = "acero",
  Hada = "hada",
}
